server:
  context-path : /wx
  session-timeout: 1800
#  port: 8099
#  https访问端口以及加密设置
  port: 444
  ssl:
    key-store: classpath:ssl.zjxpp.com.jks
    key-store-password: 6bqqpf65m2y90
    keyStoreType: JKS
logging:
  level:
    root: info
    com.cxg.weChat: debug
wechat:
#  正式机路径
  uploadPath: /var/uploaded_files/promotion/
  imagePath: file:///var/uploaded_files/promotion/
#  测试机路径
#  uploadPath: D:/var/uploaded_files/promotion/
#  imagePath: file:///D:/var/uploaded_files/promotion/
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
  resources:
      static-locations: classpath:/,classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
# 数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:exp/exp123@10.100.0.10:1530:expora
    username: exp
    password: exp123
#   druid连接池配置
    initialSize: 1
    minIdle: 10
    maxActive: 1000
    # 配置获取连接等待超时的时间
    maxWait: 120000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 200
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    host: localhost
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 10
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
# mybatis配置
mybatis:
  configuration:
      map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.cxg.weChat.**.pojo
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: redis
